# Generated by Django 3.0.8 on 2020-07-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=29)),
                ('time', models.TimeField()),
                ('adultNum', models.DecimalField(decimal_places=0, max_digits=2)),
                ('date', models.DateField()),
                ('childNum', models.DecimalField(decimal_places=0, max_digits=2)),
                ('highChair', models.DecimalField(decimal_places=0, max_digits=1)),
                ('roomNum', models.DecimalField(decimal_places=0, max_digits=3)),
                ('comment', models.CharField(max_length=199)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
