# Generated by Django 3.0.8 on 2020-07-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200724_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='time',
            field=models.TimeField(),
        ),
    ]
