# Generated by Django 3.0.8 on 2020-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200724_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='date',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='name',
            field=models.CharField(max_length=49),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
