# Generated by Django 3.0.8 on 2020-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20200724_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='date',
            field=models.TimeField(),
        ),
    ]
