# Generated by Django 3.0.8 on 2020-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200724_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='time',
            field=models.TimeField(),
        ),
    ]
